use crate::model::Layout;

pub fn restore_snapshot_sh() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail
BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$BUNDLE_DIR/snapshot/plasma-org.kde.plasma.desktop-appletsrc"
DST="$HOME/.config/plasma-org.kde.plasma.desktop-appletsrc"

[[ -f "$SRC" ]] || { echo "Snapshot missing: $SRC"; exit 1; }
mkdir -p "$HOME/.config"
[[ ! -f "$DST" ]] || cp -a "$DST" "$DST.bak.$(date -u +%Y%m%dT%H%M%SZ)"
cp -a "$SRC" "$DST"

if systemctl --user status plasma-plasmashell.service >/dev/null 2>&1; then
  systemctl --user restart plasma-plasmashell.service
else
  kquitapp6 plasmashell >/dev/null 2>&1 || true
  (plasmashell --replace >/dev/null 2>&1 & disown) || true
fi
echo "Snapshot restored."
"#
    .to_string()
}

pub fn restore_portable_sh() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail
BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLASMOIDS_DIR="$BUNDLE_DIR/plasmoids"
JS="$BUNDLE_DIR/scripts/restore-layout.js"

if [[ -d "$PLASMOIDS_DIR" ]]; then
  shopt -s nullglob
  for d in "$PLASMOIDS_DIR"/*; do
    [[ -d "$d" ]] || continue
    echo "Installing plasmoid: $d"
    kpackagetool6 -t Plasma/Applet -u "$d" >/dev/null 2>&1 || kpackagetool6 -t Plasma/Applet -i "$d"
  done
fi

[[ -f "$JS" ]] || { echo "Missing JS: $JS"; exit 1; }

QDBUS="$(command -v qdbus6 || command -v qdbus || true)"
[[ -n "$QDBUS" ]] || { echo "Need qdbus6 (qt6-tools)."; exit 1; }

echo "Applying layout via evaluateScript..."
"$QDBUS" org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "$(cat "$JS")"

if systemctl --user status plasma-plasmashell.service >/dev/null 2>&1; then
  systemctl --user restart plasma-plasmashell.service
else
  kquitapp6 plasmashell >/dev/null 2>&1 || true
  (plasmashell --replace >/dev/null 2>&1 & disown) || true
fi
echo "Portable restore complete."
"#
    .to_string()
}

pub fn restore_layout_js(layout: &Layout) -> String {
    let mut js = String::new();
    js.push_str(
        r#"// Auto-generated by plasma-layout-tui
function safePrint(x) { try { print(x); } catch (e) {} }

function writeConfigTree(widget, groupPath, kv) {
  var parts = groupPath.split("/");
  widget.currentConfigGroup = parts;
  for (var k in kv) { widget.writeConfig(k, String(kv[k])); }
}

safePrint("Starting layout restore... (additive)");
"#,
    );

    for c in &layout.containments {
        if !c.is_panel {
            continue;
        }
        js.push_str(&format!(
            r#"
safePrint("Creating panel {cid}...");
var p_{cid} = new Panel();
"#,
            cid = c.id
        ));

        for a in &c.applets {
            if let Some(pid) = &a.plugin {
                js.push_str(&format!(
                    r#"
safePrint("  addWidget {pid} (applet {aid})");
var w_{cid}_{aid} = p_{cid}.addWidget("{pid}");
"#,
                    cid = c.id,
                    aid = a.id,
                    pid = pid
                ));

                for (group, kv) in &a.config {
                    let mut obj = String::from("{");
                    let mut first = true;
                    for (k, v) in kv {
                        if !first {
                            obj.push(',');
                        }
                        first = false;
                        obj.push_str(&format!(
                            "{}:{}",
                            serde_json::to_string(k).unwrap(),
                            serde_json::to_string(v).unwrap()
                        ));
                    }
                    obj.push('}');
                    js.push_str(&format!(
                        "writeConfigTree(w_{cid}_{aid}, {g}, {obj});\n",
                        cid = c.id,
                        aid = a.id,
                        g = serde_json::to_string(group).unwrap(),
                        obj = obj
                    ));
                }
            }
        }
    }

    js.push_str(r#"safePrint("Done.");"#);
    js
}
